import { Toaster } from "react-hot-toast";
import "../styles/globals.css";

export const metadata = {
  title: "Rainbow PG",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Toaster
          position="top-right"
          reverseOrder={false}
          toastOptions={{
            duration: 5000,
          }}
        />
        <main>{children}</main>
      </body>
    </html>
  );
}
